Repository TeamAlpha5/AirViewer2, pull requests merged in 2022-04, with the labels that each got.

#26 Adding dependencies for converting Pdf into Picture formats
  pom.xml
Labels: Code changes

#22 Adding UI buttons for converting Pdf into Picture formats
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: UI Enhancement

#27 Adding rotate pdf button
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: UI Enhancement

#31 Adding the function for converting PDF to JPEG
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: add function

#30 Adding rotate functionality
  pom.xml
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: add function

#36 Adding the function for converting PDF to PNG
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: add function

#50 Adding JPEG.java file that converts PDF to JPEG
  src/main/java/edu/wright/airviewer2/JPEG.java
Labels: add function

#51 Adding methods that are required for merging pdfs
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: Code changes

#53 Adding UI button for Merging Pdf
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: UI Enhancement

#58 Adding PNG.java file for Pdf to PNG conversion
  src/main/java/edu/wright/airviewer2/PNG.java
Labels: add function

#59 Adding UI button for Split Pdfs
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: UI Enhancement

#60 Adding Add Page button to add an empty page to the pdf
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: UI Enhancement

#61 Adding MergePdf.java file which is used to merge two pdfs
  src/main/java/edu/wright/airviewer2/MergePdf.java
Labels: add function

#62 Linking Add Page button from fxml document to controller file
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: enhancement

#64 Adding Java File which is used to perform split functionality
  src/main/java/edu/wright/airviewer2/SplitPdf.java
Labels: Task for User Story 6, add function

#63 Adding function for 'Add Page' button
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: add function

#66 Adding Method for Merge Button
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: add function

#68 Improving add page functionality
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: enhancement

#69 Improving rotate functionality
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: enhancement

#70 Adding Split Function for Split Button
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: Task for User Story 6, add function

#83 Adding dependencies that required for converting PDF into file formats
  pom.xml
Labels: add function

#84 Adding UI buttons which required for converting PDF into file formats
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: add function

#87 Added class file for rotate functionality
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/java/edu/wright/airviewer2/RotateViewerModel.java
Labels: add function

#97 Uploading the JPEG test file which is used to test the conversion of PDF to JPEG format
  src/test/java/edu/wright/airviewer2/TestJPEG.java
Labels: Test file

#96 Adding java class to add empty page functionality
  src/main/java/edu/wright/airviewer2/AddPageInPDF.jaa
Labels: add function

#99 Adding remove button and linking to controller file
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: enhancement, UI Enhancement

#98 Uploading the PNG test file which is used to test the conversion of P…
  src/test/java/edu/wright/airviewer2/TestPNG.java
Labels: Test file

#106 Adding the function calls for doc,text,html which are used for convert…
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: Code changes

#100 Adding class for remove functionality
  src/main/java/edu/wright/airviewer2/RemovePageInPDF.java
Labels: add function

#107 Linking encrypt button with controller file
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: enhancement

#108 Adding the class file for encrypt functionality
  src/main/java/edu/wright/airviewer2/EncryptPDF.java
Labels: add function

#109 Adding JUnit test file for testing rotate functionality
  src/test/java/edu/wright/airviewer2/RotateViewerModelTest.java
Labels: add function

#110 Adding JUnit test file for testing add page functionality
  src/test/java/edu/wright/airviewer2/AddPageInPDFTest.java
Labels: add test

#111 Adding JUnit test file for testing remove page functionality
  src/test/java/edu/wright/airviewer2/RemovePageInPDFTest.java
Labels: add test

#114 Adding JUnit test file for testing encrypt pdf functionality
  src/test/java/edu/wright/airviewer2/EncryptPDFTest.java
Labels: add test

#115 Adding java file which is used for converting pdf to document format
  src/main/java/edu/wright/airviewer2/DocConversion.java
Labels: add function

#117 Adding java file which is used for converting pdf to Html format
  src/main/java/edu/wright/airviewer2/HtmlConversion.java
Labels: add function

#116 Adding encrypt and decrypt buttons
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: UI Enhancement

#118 Adding java file which is used for converting pdf to Text format
  src/main/java/edu/wright/airviewer2/TextConversion.java
Labels: add function

#119 Adding Junit test file which is used to test the conversion of pdf to…
  src/test/java/edu/wright/airviewer2/TestDocConversion.java
Labels: add function

#120 Adding Junit test file which is used for testing the conversion of pd…
  src/test/java/edu/wright/airviewer2/TextConversionTest.java
Labels: Test file

#121 Adding Junit test file which is used to test the conversion of pdf to…
  src/test/java/edu/wright/airviewer2/HtmlConversionTest.java
Labels: Test file

#122 Adding Test File which is used to test the functionality of MergePdf …
  src/test/java/edu/wright/airviewer2/TestMergePdf.java
Labels: Test file, add test

#123 Adding the functionality of watermark addition to the Pdf and adding UI button in the interface for watermark addition
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: UI Enhancement, add function

#130 Adding the java file which is required for the addition of the waterm…
  src/main/java/edu/wright/airviewer2/Watermarkaddition.java
Labels: add function

#131 Adding Junit test file which is used to test the addition of watermar…
  src/test/java/edu/wright/airviewer2/WatermarkadditionTest.java
Labels: Test file

#132 Added functionality for page navigation in the AirViewercontroller class and added the tags for generating button for pagination in fxml file
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: Code changes, add function

#133 I added the functionality of scroller and added the required imports and initialized the scroller method and removed a scroller MenuItem disable line from a refresh user interface method.
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: Code changes, add function

#134 Adding UI Button for Protect Password and also adding method in controller file for protect password functionality
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: UI Enhancement, Code changes

#135 Adding the class file for protect pdf functionality
  src/main/java/edu/wright/airviewer2/PdfPassword.java
Labels: add function

#141 Adding Junit Test file which is used to test the protect password fun…
  src/test/java/edu/wright/airviewer2/PdfPasswordTest.java
Labels: add test

#137 Added Required imports and buttons for Zoom functionality
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: Code changes

#142 Adding Junit Test File for testing split functionality
  src/test/java/edu/wright/airviewer2/TestSplit.java
Labels: add test

#144 Adding the class file for PdfOptimization Functionality
  PdfOptimization.java
Labels: Code changes

#148 Adding Junit Test File for Optimize Functionality
  src/test/java/edu/wright/airviewer2/PdfOptimizationTest.java
Labels: Test file

#149 Adding the java file which is used to add header to the pdf
  src/main/java/edu/wright/airviewer2/HeaderAddition.java
Labels: add function

#151 Adding Junit Test File to test the functionality of Header Function
  src/test/java/edu/wright/airviewer2/TestHeader.java
Labels: add test

#153 Adding JUnit Test File to test the functionality of Footer function
  src/test/java/edu/wright/airviewer2/TestFooter.java
Labels: add test

#143 Written Code for Zoom functionality and added required imports and annotations for method implementation.
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/java/edu/wright/airviewer2/AnnotationDialog.java
Labels: add function

#156 Added a new class Annotation Dialog Box for generating a pop up box to set box parameters and add text to type of annotation box
  src/main/java/edu/wright/airviewer2/AnnotationDialog.java
Labels: add function

#155 I have created a class for image functionality for generating a dialog box to open the image by providing the size and height of the image.
  src/main/java/edu/wright/airviewer2/ImageAnnotationDialog.java
Labels: Code changes, add function

#157 i have uploaded a java file to set height and width of the image and the image will be opened by the dimensions given in the image annotation dialog box.
  src/main/java/edu/wright/airviewer2/ImageAnnotationMaker.java
Labels: Code changes, add function

#164 Adding UI changes as well as method which is used to invoke add image Functionality.
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: Code changes, add function

#165 Added a method that shows annotation dialog with title and size of the box values and made changes in the add box annotation event handler class
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: Code changes, add function

#166 Added the button for add image functionality with required imports.
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: Code changes

#167 Changes have been made in eclipse annotation and text annotation action event methods
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
Labels: Code changes

#173 Adding the functionality of stamp addition to the Pdf and adding UI button in the interface for adding stamp to the Pdf
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: UI Enhancement, Code changes, add function

#174 Adding java file which is used for addition of stamp to the Pdf
  src/main/java/edu/wright/airviewer2/PdfStamp.java
Labels: add function

#175 Adding Junit test file which is used to test the addition of stamp to the pdf
  src/test/java/edu/wright/airviewer2/TestPdfStamp.java
Labels: Test file, add test

#179 Adding the test file which is required for testing the image functionality.
  src/test/java/edu/wright/airviewer2/TestImage.java
Labels: add test

#180 Need to test the functionality of Image Annotation Dialog.
  src/test/java/edu/wright/airviewer2/TestImageAnnotationDialog.java
Labels: add test

#181 Adding the test file which is used for testing Image Annotation Maker.
  src/test/java/edu/wright/airviewer2/TestImageannotationsmaker.java
Labels: add test

#182 Adding the test file which is used for testing scroller functionality.
  src/test/java/edu/wright/airviewer2/TestScroller.java
Labels: add test

#187 Added test class for box annotation
  src/test/java/edu/wright/airviewer2/BoxannotationTest.java
Labels: add test

#188 Added test class for Eclipse annotation
  src/test/java/edu/wright/airviewer2/EclipseannotationTest.java
Labels: add test

#189 Added Test class for Text annotation
  src/test/java/edu/wright/airviewer2/TextannotationTest.java
Labels: add test

#190 Added Test class for Zoom In and Zoom Out functionality
  src/test/java/edu/wright/airviewer2/ZoombuttonFunctionalityTest.java
Labels: add test

#191 Added test class for Zoom buttons to test it's width, height and zoom type
  src/test/java/edu/wright/airviewer2/UpdatezoomfactorTest.java
Labels: add test

#197 Added UI button and functionality for converting PDF file to BMP file format.
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: UI Enhancement, add function

#198 Added a class file which is used for converting PDF file to BMP format.
  src/main/java/edu/wright/airviewer2/BMPConversion.java
Labels: add function

#200 Added a test file which is used to test the functionality of converting PDF format to BMP format.
  src/test/java/edu/wright/airviewer2/BMPConversionTest.java
Labels: Test file, add test

#206 Added UI button and written lines of code for converting Pdf to Ppt
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: UI Enhancement, Code changes

#207 Added a class with functionality to convert pdf to ppt file
  src/main/java/edu/wright/airviewer2/PPTConversion.java
Labels: add function

#208 Added a test class to test the convert to ppt functionality
  src/test/java/edu/wright/airviewer2/PPTConversionTest.java
Labels: add test

#205 Adding comments to increase the readability by following the characteristics of Literate Programming
  src/main/java/edu/wright/airviewer2/FooterAddition.java
  src/main/java/edu/wright/airviewer2/HeaderAddition.java
  src/main/java/edu/wright/airviewer2/MergePdf.java
  src/main/java/edu/wright/airviewer2/PdfOptimization.java
  src/main/java/edu/wright/airviewer2/PdfPassword.java
  src/main/java/edu/wright/airviewer2/SplitPdf.java
Labels: Literate Programming

#210 Adding comments which is used to increase the readability by following the characteristics of Literate Programming
  src/main/java/edu/wright/airviewer2/HtmlConversion.java
  src/main/java/edu/wright/airviewer2/JPEG.java
  src/main/java/edu/wright/airviewer2/PNG.java
  src/main/java/edu/wright/airviewer2/PdfStamp.java
  src/main/java/edu/wright/airviewer2/TextConversion.java
  src/main/java/edu/wright/airviewer2/Watermarkaddition.java
Labels: Literate Programming

#213 Adding comments which are used to increase the readability of the code.
  src/main/java/edu/wright/airviewer2/BMPConversion.java
  src/main/java/edu/wright/airviewer2/ImageAnnotationDialog.java
  src/main/java/edu/wright/airviewer2/ImageAnnotationMaker.java
Labels: Literate Programming

#212 Documentation for programming by contract is created and adding it.
  Program By Contract/Program By Contract by Ram Dixit Erra.md
Labels: Program by Contract

#211 Adding program by contract documentation
  Program By Contract/Program by Contract by Rahul Satla.md
Labels: Program by Contract

#214 Adding Program by Contract document.
  Program by Contract/Program by Contract by Akhil Sabbella.md
Labels: Program by Contract

#215 Added documentation for Program by contract
  Program By Contract/Program By Contract by Deepika Gadiraju.md
Labels: Program by Contract

#216 Adding documentation for Program By Contract
  Program By Contract/Program by contract by Ravali Satla.md
Labels: Program by Contract

#217 Adding Program by Contract document.
  Program By Contract/Program by Contract by Akhil Sabbella.md
Labels: Program by Contract

#218 Adding Software Design Document for sprint1
  Software Design Document for Sprint 1.zip
Labels: documentation, Software Design Document

#219 Adding Final Software Design Document (SSD)
  Final Software Design Document.zip
Labels: documentation, Software Design Document

#220 Adding Document Of Spring1 Retrospective.md
  Spring1Retrospective.md
Labels: documentation

#221 Added Document About Sprint2 Retrospective
  Spring2Retrospective.md
Labels: documentation

#222 Adding the test coverage file for header
  Test Coverage/Test Coverage for Header file.zip
Labels: Test Coverage

#223 Adding the test coverage file for Pdfoptimization
  Test Coverage/PdfOptimizationCoverage.zip
Labels: Test Coverage

#225 Adding the test coverage file for Footer
  Test Coverage/Test Coverage for footer.zip
Labels: Test Coverage

#227 Adding the test coverage file for JPEG class file
  Test Coverage/TestJpegCodeCoverage.zip
Labels: Test Coverage

#228 Added Test coverage file for PPTConverter
  Test Coverage/PPTTestCoverage.zip
Labels: Test Coverage

#229 Adding the test coverage file for PNG file
  Test Coverage/TestPNGCodeCoverage.zip
Labels: Test Coverage

#232 Adding the test coverage file for pdf to doc conversion file
  Test Coverage/TestDocConversionCodeCoverage.zip
Labels: Test Coverage

#226 Adding the test coverage file for BMP converter
  Test Coverage/BMPConversionTestCoverage.zip
Labels: Test Coverage

#231 Adding Test coverage files
  Test Coverage/AddPageinPDFTest.zip
  Test Coverage/EncryptPDFTest.zip
  Test Coverage/RemovePageInPDFTest.zip
  Test Coverage/RotateViewerModelTest.zip
Labels: Test Coverage

#234 Adding Test Coverage file for PdfPassword
  Test Coverage/PdfPassword.zip
Labels: Test Coverage

#233 Adding the test coverage file for html conversion
  Test Coverage/HtmlConversionCodeCoverage.zip
Labels: Test Coverage

#236 Adding the test coverage file for text conversion
  Test Coverage/TextConversionCodeCoverage.zip
Labels: Test Coverage

#235 Adding the test coverage file for MergePdf File
  Test Coverage/MergePdf.zip
Labels: Test Coverage

#238 Adding the test coverage file for addition of stamp to the pdf
  Test Coverage/TestPdfStampCodeCoverage.zip
Labels: Test Coverage

#237 Adding a product backlog document
  product backlog.txt
Labels: product backlog

#240 Updated the complete Pom.xml file since old pom.xml file gives errors in code while executing.
  pom.xml
Labels: Code changes

#242 Enhancing the previous version of Product.md file by using the github interface for better understanding and readability
  product backlog.md
  product backlog.txt
Labels: product backlog

#243 Adding comments to increase the readability of the code.
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/java/edu/wright/airviewer2/PPTConversion.java
Labels: Literate Programming

#244 Added Test coverage for box Annotation class.
  Test Coverage/BoxAnnotationTest.zip
Labels: Test Coverage

#245 Added test coverage for test image annotation dialog.
  Test Coverage/TestAnnotationImageDialog.zip
Labels: Test Coverage

#246 Added Test coverage for Eclipse annotation class.
  Test Coverage/EclipseAnnotationTest.zip
Labels: Test Coverage

#247 Added Test coverage for Text annotation class
  Test Coverage/TextAnnotationTest.zip
Labels: Test Coverage
